# Generated by Django 5.2.17 on 2026-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cuisines',
            field=models.CharField(blank=True, default='indian biryani', help_text='Space-separated tags for filtering, e.g. indian biryani', max_length=200),
        ),
    ]
